### ISSUE TITLE
Resource Filtering Error

### ISSUE THREAD

**Issue by saramaebee** [codesupport/website-frontend#18]
[Gif of it in action](https://cdn.discordapp.com/attachments/720675421837983854/743182239466127451/website_bug.gif)

When adjusting the filters on the resource page, adjusting a filter resets any other filter

**Comment by shyguy2601** [comment]
@LamboCreeper I reckon I can fix this

**Comment by shyguy2601** [comment]
Sorry I forgot to say that I changed my mind on this, I came across IRL problems :/

**Comment by ryboh1** [comment]
I'm going to give this a shot :)

**Comment by ryboh1** [comment]
Okay, I fixed the bug and committed.

Please tell me if you have received the commit, as first time committing to a repo that isn't my own. 

**However there is another bug I ran into**
if you "Filter by category" value CSS
and 
"filter by price" value paid
The result is a continuous loading screen. 

This isn't because the website is loading but because there aren't any CSS paid resources.

**Comment by JonaVDM** [comment]
The problem seems to be also there with the search bar, I assume we want the list to match all 3 of the categories (search, category and price). This is also present with Ryan's fix.
